import 'dotenv/config'; // load .env

export const KAFKA_TOPICS = {
  USER_ACTION_REQUESTED: process.env.KAFKA_USER_ACTION_REQUESTED || '',
  USER_ACTION_REQUESTED_DLQ: process.env.KAFKA_USER_ACTION_REQUESTED_DLQ || '',
  USER_ACTION_VALIDATED: process.env.KAFKA_USER_ACTION_VALIDATED || '',
  USER_ACTION_VALIDATED_DLQ: process.env.KAFKA_USER_ACTION_VALIDATED_DLQ || '',
} as const;

export const KAFKA_DLQ_MAP: Record<string, string> = {
  [KAFKA_TOPICS.USER_ACTION_REQUESTED]: KAFKA_TOPICS.USER_ACTION_REQUESTED_DLQ,
  [KAFKA_TOPICS.USER_ACTION_VALIDATED]: KAFKA_TOPICS.USER_ACTION_VALIDATED_DLQ,
};
